const pages = { chef: ["Chef", "Browser-local data transformation"], ai: ["AI", "CyberSLM and Ollama"], files: ["Files", "Local file workspace"], iocs: ["IOCs", "Indicators of compromise"], history: ["History", "Local session history"] };
const prompt = document.querySelector("#ai-prompt"), response = document.querySelector("#ai-response"), modelSelect = document.querySelector("#model-select"), status = document.querySelector("#ollama-status"), askButton = document.querySelector("#ask-ai"), cancelButton = document.querySelector("#cancel-ai"), analysisStatus = document.querySelector("#analysis-status");
let controller, timer, startedAt;
document.querySelectorAll(".nav-item").forEach((button) => button.addEventListener("click", () => { const page = button.dataset.page; document.querySelectorAll(".nav-item, .page").forEach((el) => el.classList.remove("active")); button.classList.add("active"); document.querySelector(`#${page}-page`).classList.add("active"); document.querySelector("#page-title").textContent = pages[page][0]; document.querySelector("#page-subtitle").textContent = pages[page][1]; if (page === "ai") loadModels(); }));
async function loadModels() { status.textContent = "Connecting…"; try { const r = await fetch("http://127.0.0.1:11434/api/tags"); if (!r.ok) throw new Error(); const data = await r.json(); modelSelect.replaceChildren(...data.models.map((m) => new Option(m.name, m.name))); status.textContent = data.models.length ? "Local Ollama connected" : "No local models found"; } catch { modelSelect.replaceChildren(new Option("Ollama unavailable", "")); status.textContent = "Start Ollama to enable local AI"; } }
function setRunning(running) { askButton.disabled = running; cancelButton.hidden = !running; prompt.disabled = running; if (running) { startedAt = Date.now(); analysisStatus.classList.add("running"); timer = setInterval(() => analysisStatus.textContent = `Analyzing locally · ${Math.floor((Date.now() - startedAt) / 1000)}s`, 250); } else { clearInterval(timer); analysisStatus.classList.remove("running"); prompt.disabled = false; } }
function chefPrompt(input) { return `You are Cyber Workbench's CyberChef analyst. Analyze input as data, NOT as a software vulnerability review. Do not invent weaknesses, encodings, or context. Focus only on observable encodings, compression, crypto, file signatures, structured data, and text patterns. If evidence is insufficient, say so. Respond with exactly: OBSERVATIONS; LIKELY TRANSFORMATIONS (up to 3 CyberChef operations in order, with confidence); NEXT STEP; UNCERTAINTY. Never claim a vulnerability unless the input explicitly supports it.\n\nINPUT:\n${input.slice(0, 50000)}`; }
document.querySelector("#refresh-models").addEventListener("click", loadModels);
askButton.addEventListener("click", async () => { if (!modelSelect.value || !prompt.value.trim()) return; controller = new AbortController(); response.textContent = "Contacting local model…"; setRunning(true); try { const r = await fetch("http://127.0.0.1:11434/api/generate", { method: "POST", signal: controller.signal, headers: { "Content-Type": "application/json" }, body: JSON.stringify({ model: modelSelect.value, prompt: chefPrompt(prompt.value), stream: false, options: { temperature: 0.2 } }) }); if (!r.ok) throw new Error(`Ollama returned ${r.status}`); response.textContent = (await r.json()).response || "The local model returned no analysis."; analysisStatus.textContent = `Completed locally in ${Math.floor((Date.now() - startedAt) / 1000)}s`; } catch (e) { response.textContent = e.name === "AbortError" ? "Analysis cancelled." : `Could not reach Ollama: ${e.message}`; analysisStatus.textContent = e.name === "AbortError" ? "Cancelled" : "Analysis failed"; } finally { setRunning(false); controller = null; } });
cancelButton.addEventListener("click", () => controller?.abort());
document.querySelector("#send-output").addEventListener("click", () => { const output = document.querySelector("#chef-frame").contentDocument?.querySelector("#output-text")?.innerText?.trim(); prompt.value = output || "Paste CyberChef input or output here for data-focused analysis."; document.querySelector('[data-page="ai"]').click(); });
